language: node_js
node_js:
  - "18"
  - "20"

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      script: yarn run ci-test
    - stage: release
      if: branch = master AND type != pull_request
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
