name: Main
on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  # for checkout
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      # to be able to publish a GitHub release
      contents: write
      # to be able to comment on released issues
      issues: write
      # to be able to comment on released pull requests
      pull-requests: write
      # to enable use of OIDC for npm provenance
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run ci-test

      - name: Report code coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm exec semantic-release
